now the flow can create new launch template version

diff --git a/.github/workflows/artifact.yml b/.github/workflows/artifact.yml
--- a/.github/workflows/artifact.yml
+++ b/.github/workflows/artifact.yml
@@ -118,7 +118,7 @@ jobs:
 
     env:
       AWS_REGION: ${{ secrets.AWS_REGION }}
-      DEPLOY_ENVIRONMENT: ${{ secrets.DEPLOY_ENVIRONMENT }}
+      DEPLOY_ENVIRONMENT_ACCOUNT: ${{ secrets.DEPLOY_ENVIRONMENT_ACCOUNT }}
       LAUNCH_TEMPLATE_ID: ${{ secrets.LAUNCH_TEMPLATE_ID }}
       AUTO_SCALING_GROUP_NAME: ${{ secrets.AUTO_SCALING_GROUP_NAME }}
 
@@ -135,18 +135,66 @@ jobs:
           echo "AMI_ID: $AMI_ID"
           echo "ami_id=$AMI_ID" >> $GITHUB_ENV
 
+      # configure credentials based on the environment
+
       - name: Configure AWS Credentials for Dev
-        if: ${{ env.DEPLOY_ENVIRONMENT == 'dev' }}
-        uses: aws-actions/configure-aws-credentials@v1
+        if: ${{ env.DEPLOY_ENVIRONMENT_ACCOUNT == 'dev' }}
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
       - name: Configure AWS Credentials for Demo
-        if: ${{ env.DEPLOY_ENVIRONMENT == 'demo' }}
-        uses: aws-actions/configure-aws-credentials@v1
+        if: ${{ env.DEPLOY_ENVIRONMENT_ACCOUNT == 'demo' }}
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}
           aws-region: ${{ env.AWS_REGION }}
+
+      # create the new template version with new ami id
+
+      - name: Create New Template Version
+        id: create_lt_version
+        run: |
+          AMI_ID=${{ env.ami_id }}
+          echo "Creating new Launch Template version with AMI ID: $AMI_ID"
+          aws ec2 create-launch-template-version \
+              --launch-template-id ${{ env.LAUNCH_TEMPLATE_ID }} \
+              --source-version 1 \
+              --launch-template-data "{\"ImageId\":\"$AMI_ID\"}" \
+              --no-cli-pager
+
+      # Start Instance Refresh for Auto Scaling Group
+      - name: Start Instance Refresh
+        id: start_refresh
+        run: |
+          REFRESH_ID=$(aws autoscaling start-instance-refresh \
+              --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }} \
+              --query "InstanceRefreshId" \
+              --output text \
+              --no-cli-pager)
+          echo "Instance Refresh started with ID: $REFRESH_ID"
+          echo "instance_refresh_id=$REFRESH_ID" >> $GITHUB_ENV
+
+      # Wait for Instance Refresh to complete the work
+      - name: Wait for Instance Refresh Completion
+        run: |
+          echo "Waiting for instance refresh to complete..."
+          while true; do
+            STATUS=$(aws autoscaling describe-instance-refreshes \
+                --auto-scaling-group-name ${{ env.AUTO_SCALING_GROUP_NAME }} \
+                --query "InstanceRefreshes[?InstanceRefreshId=='${{ env.instance_refresh_id }}'].Status" \
+                --output text \
+                --no-cli-pager)
+            echo "Current status: $STATUS"
+            if [[ "$STATUS" == "Successful" ]]; then
+              echo "Instance Refresh completed successfully."
+              break
+            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" ]]; then
+              echo "Instance Refresh failed or was cancelled. Exiting."
+              exit 1
+            fi
+            sleep 30
+          done
